general.import = ["~/.config/alacritty/themes/coolnight.toml"]

[ env ]
TERM = "xterm-256color"
GTK_IM_MODULE = "fcitx5"
QT_IM_MODULE = "fcitx5"
XMODIFIERS = "@im=fcitx5"

[window]
padding.x = 15
padding.y = 15

decorations = "Buttonless"

[font]
normal.family = "0xProto Nerd Font"
size = 18
